name: GitHub Actions Demo

on:
  push: 
    branches: main
    paths-ignore: './github/*'
  pull_request:
    branches: main
  schedule:
    # Sunday at 6:15 am UTC
    -  '15 06 * * 0'
  workflow_dispatch: 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github['event_name'] }} event."
